// championData.js - Base de données COMPLÈTE des champions RSL
// Source: https://www.alucare.fr (Décembre 2025)
// Il manque encore les champions épiques et rares src=https://www.alucare.fr/wiki/guide-raid-shadow-legend/liste-des-champions-de-raid-shadow-legends-par-rarete-et-force/

const champions = [
    // ==================== MYTHIQUES ====================

    // Mythique Rang S (God Tier) - 7 champions
    { name: "Alaz Porte-soleil", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-alaz-artefact-et-maitrise/" },
    { name: "Dame Mikage", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dame-mikage-artefact-et-maitrise/" },
    { name: "Hiérophante Lazarius", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hierophante-lazarius-artefact-et-maitrise/" },
    { name: "Nell Dents-noires", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nell-dents-noires-artefact-et-maitrise/" },
    { name: "Polara Cœur-de-feu", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-polara-coeur-de-feu-artefact-et-maitrise/" },
    { name: "Siegfrund le Nephel", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-siegfrund-le-nephel-artefact-et-maitrise/" },
    { name: "Théodosia Disgraciée", rarity: "Mythique", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-theodosia-disgraciee-artefact-et-maitrise/" },

    // Mythique Rang A (Excellent) - 11 champions
    { name: "Ash'nar Âme-dragon", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ashnar-ame-dragon-artefact-et-maitrise/" },
    { name: "Arbais Pierrépine", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arbais-pierrepine-artefact-et-maitrise/" },
    { name: "Embrys l'Anomalie", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-embrys-lanomalie-artefact-et-maitrise/" },
    { name: "Fjorad Cœur-de-loup", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fjorad-coeur-de-loup-equipement-et-maitrise/" },
    { name: "Galathir Sage-astral", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galathir-sage-astral-artefact-et-maitrise/" },
    { name: "Gharol Masse-Sang", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gharol-masse-sang-artefact-et-maitrise/" },
    { name: "Gizmak le Terrible", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gizmak-le-terrible-artefact-et-maitrise/" },
    { name: "Krixia Reine de Nuit", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-krixia-reine-de-nuit-artefact-et-maitrise/" },
    { name: "Kurosa l'Envieuse", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kurosa-lenvieuse-artefact-et-maitrise/" },
    { name: "Naïs Voleur d'Ombres", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nais-voleur-dombres-artefact-et-maitrise/" },
    { name: "Toshiro le sanglant", rarity: "Mythique", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-toshiro-le-sanglant-artefact-et-maitrise/" },

    // Mythique Rang B (Bon) - 5 champions
    { name: "Galeuss Crête-sang", rarity: "Mythique", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galeuss-crete-sang-artefact-et-maitrise/" },
    { name: "Karnage l'Anarque", rarity: "Mythique", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-karnage-lanarque-artefact-et-maitrise/" },
    { name: "Komidus Rictus", rarity: "Mythique", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-komidus-rictus-artefact-et-maitrise/" },
    { name: "Le calamitus", rarity: "Mythique", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-le-calamitus-artefact-et-maitrise/" },
    { name: "Mezomel Croc-Loup", rarity: "Mythique", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mezomel-croc-loup-artefact-et-maitrise/" },

    // Mythique Rang C (Mauvais) - 3 champions - NE PAS FOOD
    { name: "Androc le Glorieux", rarity: "Mythique", rank: "C", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-androc-le-glorieux-artefact-et-maitrise/" },
    { name: "Aphidus Maître-ruche", rarity: "Mythique", rank: "C", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-aphidus-maitre-ruche-attaque-artefact-et-maitrise/" },
    { name: "Frolni le Mécanicien", rarity: "Mythique", rank: "C", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-frolni-le-mecanicien-artefact-et-maitrise/" },

    // ==================== LÉGENDAIRES ====================

    // Légendaire Rang S (God Tier) - 87 champions
    { name: "Xenomorphe", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-xenomorphe-artefact-et-maitrise/" },
    { name: "Predator", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-predator-artefact-et-maitrise/" },
    { name: "Gaellut Fils du Pacte", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gaellut-fils-du-pacte-et-maitrise/" },
    { name: "Jeanne la Lumineuse", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jeanne-la-lumineuse-artefact-et-maitrise/" },
    { name: "Kroz Casse-murs", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kroz-casse-murs-artefact-et-maitrise/" },
    { name: "Acrizia", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-acrizia-artefact-et-maitrise/" },
    { name: "Amiral Défense-noire", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-amiral-defense-noire-artefact-et-maitrise/" },
    { name: "Arbitre", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arbitre-equipement-et-maitrise/" },
    { name: "Artak", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-artak-artefact-et-maitrise/" },
    { name: "Authoratrix Lamasu", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-authoratrix-lamasu-equipement-et-maitrise/" },
    { name: "Bad-el-Kazar", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bad-el-kazar-equipement-et-maitrise/" },
    { name: "Ba Satha", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ba-satha-artefact-et-maitrise/" },
    { name: "Candraphon", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-candraphon-artefact-et-maitrise/" },
    { name: "Cardiel", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cardiel-artefact-et-maitrise/" },
    { name: "Choriste-lame Caldor", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-choriste-lame-caldor-artefact-et-maitrise/" },
    { name: "Dame Kimi", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dame-kimi-artefact-et-maitrise/" },
    { name: "Diacre Brogni", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-diacre-brogni-artefact-et-maitrise/" },
    { name: "Donatello", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-donatello-artefact-et-maitrise/" },
    { name: "Dracomorphe", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dracomorphe-equipement-et-maitrise/" },
    { name: "Duchesse Lilitu", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-duchesse-lilitu-equipement-et-maitrise/" },
    { name: "Elva l'Automnale", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-elva-lautomnale-artefact-et-maitrise/" },
    { name: "Énorme Ukko", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-enorme-ukko-artefact-et-maitrise/" },
    { name: "Firrol le Cornécorce", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-firrol-le-cornecorce-artefact-et-maitrise/" },
    { name: "Gaïus le joyeux", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gaius-le-joyeux-artefact-et-maitrise/" },
    { name: "Gaspard le maudit", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gaspard-le-maudit-artefact-et-maitrise/" },
    { name: "Georgid le Casseur", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-georgid-le-casseur-artefact-et-maitrise/" },
    { name: "Glaicad l'Eau-fondue", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-glaicad-leau-fondue-artefact-et-maitrise/" },
    { name: "Gnut", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gnut-artefact-et-maitrise/" },
    { name: "Graazur ventrefer", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-graazur-ventrefer-artefact-et-maitrise/" },
    { name: "Gracchos Viré-drake", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gracchos-vire-drake-artefact-et-maitrise/" },
    { name: "Helicath", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-helicath-artefact-et-maitrise/" },
    { name: "Héphraak", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hephraak-artefact-et-maitrise/" },
    { name: "Hurndig", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hurndig-artefact-et-maitrise/" },
    { name: "Jintoro", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jintoro-artefact-et-maitrise/" },
    { name: "Kael Suprême", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kael-supreme-artefact-et-maitrise/" },
    { name: "Kalvalax", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kalvalax-artefact-et-maitrise/" },
    { name: "Klaazag Géants-clés", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-klaazag-geants-cles-artefact-et-maitrise/" },
    { name: "Kreela Bras-Sorcière", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kreela-bras-sorciere-artefact-et-maitrise/" },
    { name: "Krisk l'Éternel", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-krisk-leternel-artefact-et-maitrise/" },
    { name: "Kro'khad Coupe-gorge", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-krokhad-coupe-gorge-artefact-et-maitrise/" },
    { name: "Kyoku", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kyoku-artefact-et-maitrise/" },
    { name: "Légat Téox", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-legat-teox-artefact-et-maitrise/" },
    { name: "Leonardo", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-leonardo-artefact-et-maitrise/" },
    { name: "Léorius le fier", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-leorius-le-fier-artefact-et-maitrise/" },
    { name: "Lydia Sirène de Mort", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lydia-sirene-de-mort-artefact-et-maitrise/" },
    { name: "Marichka la Robuste", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marichka-la-robuste-artefact-et-maitrise/" },
    { name: "Marius le Vaillant", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-marius-le-vaillant-artefact-et-maitrise/" },
    { name: "Martyre", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-martyre-artefact-et-maitrise/" },
    { name: "Ma'Shalled", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mashalled-artefact-et-maitrise/" },
    { name: "Mère supérieure Maud", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mere-superieure-maud-artefact-et-maitrise/" },
    { name: "Mithrala Fléaudevie", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mithrala-fleaudevie-artefact-et-maitrise/" },
    { name: "Nekhret le Terrible", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nekhret-le-terrible-artefact-et-maitrise/" },
    { name: "Nekmo Thaar", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nekmo-thaar-artefact-et-maitrise/" },
    { name: "Nergigante l'Archère", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nergigante-larchere-artefact-et-maitrise/" },
    { name: "Nethril", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nethril-artefact-et-maitrise/" },
    { name: "Niamhe, Lance de Nyresa", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-niamhe-lance-de-nyresa-artefact-et-maitrise/" },
    { name: "Ninja", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ninja-artefact-et-maitrise/" },
    { name: "Othorion le Maître", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-othorion-le-maitre-artefact-et-maitrise/" },
    { name: "Pheidi Crête-Bleue", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pheidi-crete-bleue-artefact-et-maitrise/" },
    { name: "Prince Kymar", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-prince-kymar-artefact-et-maitrise/" },
    { name: "Pythion", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pythion-artefact-et-maitrise/" },
    { name: "Quintus le Triomphal", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-quintus-le-triomphal-artefact-et-maitrise/" },
    { name: "Ragash", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ragash-artefact-et-maitrise/" },
    { name: "Raglin", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-raglin-artefact-et-maitrise/" },
    { name: "Ramantu Sang-Drake", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ramantu-sang-drake-artefact-et-maitrise/" },
    { name: "Reine de Cœur", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-reine-de-coeur-artefact-et-maitrise/" },
    { name: "Rotos le Marié Egaré", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rotos-le-marie-egare-artefact-et-maitrise/" },
    { name: "Scyl des Drakes", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-scyl-des-drakes-artefact-et-maitrise/" },
    { name: "Seigneur de guerre", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-seigneur-de-guerre-equipement-et-maitrise/" },
    { name: "Seigneur Tombeau", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-seigneur-tombeau-artefact-et-maitrise/" },
    { name: "Sicia Languefeu", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sicia-languefeu-artefact-et-maitrise/" },
    { name: "Sieur Nicolas", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sieur-nicolas-artefact-et-maitrise/" },
    { name: "Siphi Mariée Égarée", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-siphi-mariee-egaree-artefact-et-maitrise/" },
    { name: "Sire amuseur Fabian", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sire-amuseur-fabian-artefact-et-maitrise/" },
    { name: "Staltus Fléau-dragon", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-staltus-fleau-dragon-artefact-et-maitrise/" },
    { name: "Sulfuryion", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sulfuryion-artefact-et-maitrise/" },
    { name: "Taras le Farouche", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-taras-le-farouche-artefact-et-maitrise/" },
    { name: "Téodor le Savant", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-teodor-le-savant-artefact-et-maitrise/" },
    { name: "Tetsuya le Sauveur", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tetsuya-le-sauveur-artefact-et-maitrise/" },
    { name: "Teumesia", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-teumesia-artefact-et-maitrise/" },
    { name: "Titus Plume-noire", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-titus-plume-noire-artefact-et-maitrise/" },
    { name: "Tormin le Froid", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tormin-le-froid-artefact-et-maitrise/" },
    { name: "Trunda MailletDoré", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-trunda-mailletdore-artefact-et-maitrise/" },
    { name: "Turvold", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-turvold-artefact-et-maitrise/" },
    { name: "Urost Capturâme", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-urost-capturame-artefact-et-maitrise/" },
    { name: "Ursuga Hurleguerre", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ursuga-hurleguerre-artefact-et-maitrise/" },
    { name: "Valkyrie", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valkyrie-artefact-et-maitrise/" },
    { name: "Vénus", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-venus-artefact-et-maitrise/" },
    { name: "Vulkanos Fumor", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vulkanos-fumor-artefact-et-maitrise/" },
    { name: "Yncensa Porte-graal", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yncensa-porte-graal-artefact-et-maitrise/" },
    { name: "Yumeko", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yumeko-artefact-et-maitrise/" },
    { name: "Zavia", rarity: "Légendaire", rank: "S", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zavia-artefact-et-maitrise/" },

    // Légendaire Rang A (Excellent) - 172 champions
    { name: "Abbesse", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-abbesse-artefact-et-maitrise/" },
    { name: "Acelin le Vaillant", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-acelin-le-vaillant-artefact-et-maitrise/" },
    { name: "Ailil", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ailil-artefact-et-maitrise/" },
    { name: "Alatreon l'Epeiste", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-alatreon-lepeiste-artefact-et-maitrise/" },
    { name: "Alice la Flâneuse", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-alice-la-flaneuse-artefact-et-maitrise/" },
    { name: "Alsgor Corne-Pourpre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-alsgor-corne-pourpre-artefact-et-maitrise/" },
    { name: "Altan", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-altan-artefact-et-maitrise/" },
    { name: "Amoch la Satrape", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-amoch-la-satrape-artefact-et-maitrise/" },
    { name: "Angar", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-angar-artefact-et-maitrise/" },
    { name: "Aragaz Roi-sauvage", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-aragaz-roi-sauvage-artefact-et-maitrise/" },
    { name: "Arashi le Ressac", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arashi-le-ressac-equipement-et-maitrise/" },
    { name: "Arathéia Fleur-corps", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-aratheia-fleur-corps-artefact-et-maitrise/" },
    { name: "Archevêque Pinthroy", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-archeveque-pinthroy-artefact-et-maitrise/" },
    { name: "Armanz le Sublime", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-armanz-le-sublime-artefact-et-maitrise/" },
    { name: "Arnorn l'Éclatant", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arnorn-leclatant-artefact-et-maitrise/" },
    { name: "Astralon", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-astralon-artefact-et-maitrise/" },
    { name: "Baron", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-baron-artefact-et-maitrise/" },
    { name: "Bélanor", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-belanor-artefact-et-maitrise/" },
    { name: "Belletar Tue-mages", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-belletar-tue-mages-artefact-et-maitrise/" },
    { name: "Belz le Vengeur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-belz-le-vengeur-artefact-et-maitrise/" },
    { name: "Bivald de l'Épine", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bivald-de-lepine-artefact-et-maitrise/" },
    { name: "Blizaar le Braillard", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-blizaar-le-brillard-artefact-et-maitrise/" },
    { name: "Bolint l'Affranchi", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bolint-laffranchi-artefact-et-maitrise/" },
    { name: "Boragar l'Ancien", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-boragar-lancien-artefact-et-maitrise/" },
    { name: "Brago d'Acier", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-brago-dacier-artefact-et-maitrise/" },
    { name: "Brakus le métamorphe", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-brakus-le-metamorphe-artefact-et-maitrise/" },
    { name: "Caoilte Flèchecendre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-caoilte-flechecendre-artefact-et-maitrise/" },
    { name: "Chaagur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chaagur-artefact-et-maitrise/" },
    { name: "Chalco l'Aveugle", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chalco-laveugle-equipement-et-maitrise/" },
    { name: "Chantre-dune Zaharis", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chantre-dune-zaharis-equipement-et-maitrise/" },
    { name: "Chapelier fou", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chapelier-fou-artefact-et-maitrise/" },
    { name: "Chasseur Royal", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chasseur-royal-artefact-et-maitrise/" },
    { name: "Chat du Cheshire", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chat-du-cheshire-artefact-et-maitrise/" },
    { name: "Chevalier Suprême", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chevalier-supreme-artefact-et-maitrise/" },
    { name: "Claidna", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-claidna-artefact-et-maitrise/" },
    { name: "Cléoptérix", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cleopterix-artefact-et-maitrise/" },
    { name: "Comtesse Lix", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-comtesse-lix-artefact-et-maitrise/" },
    { name: "Corvis Le Corrupteur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-corvis-le-corrupteur-artefact-et-maitrise/" },
    { name: "Crohnam", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-crohnam-artefact-et-maitrise/" },
    { name: "Cruetraxa", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cruetraxa-artefact-et-maitrise/" },
    { name: "Cupidon", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cupidon-artefact-et-maitrise/" },
    { name: "Dame Ireth", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dame-ireth-artefact-et-maitrise/" },
    { name: "Dame Noëlle", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dame-noelle-artefact-et-maitrise/" },
    { name: "Danag Fauchecrâne", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-danag-fauchecrane-artefact-et-maitrise/" },
    { name: "Diamant Pièce-cuivre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-diamant-piece-cuivre-artefact-et-maitrise/" },
    { name: "Dreng La Tombe", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-dreng-la-tombe-artefact-et-maitrise/" },
    { name: "Drexthar Doublesang", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-drexthar-doublesang-artefact-et-maitrise/" },
    { name: "Elhain Suprême", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-elhain-supreme-artefact-et-maitrise/" },
    { name: "Esmé la Danseuse", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-esme-la-danseuse-equipement-et-maitrise/" },
    { name: "Emic Coeur-Tronc", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-emic-coeur-tronc-artefact-et-maitrise/" },
    { name: "Eostrid chant-rêve", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-eostrid-chant-reve-artefact-et-maitrise/" },
    { name: "Falmond Lamedeuil", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-falmond-lamedeuil-artefact-et-maitrise/" },
    { name: "Foli", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-foli-artefact-et-maitrise/" },
    { name: "Fortus", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fortus-artefact-et-maitrise/" },
    { name: "Freyja du Destin", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-freyja-du-destin-artefact-et-maitrise/" },
    { name: "Fu-Shan", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fu-shan-artefact-et-maitrise/" },
    { name: "Fyna, lame d'Aravia", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fyna-lame-daravia-artefact-et-maitrise/" },
    { name: "Gamuran", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gamuran-artefact-et-maitrise/" },
    { name: "Garde-Caveau", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-wixwell-garde-caveau-artefact-et-maitrise/" },
    { name: "Garde-bière Jéroboam", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-garde-biere-jeroboam-artefact-et-maitrise/" },
    { name: "Genzin", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-genzin-artefact-et-maitrise/" },
    { name: "Giath Écu de vérité", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-giath-ecu-de-verite-artefact-et-maitrise/" },
    { name: "Gliseah Guidâme", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gliseah-guidame-artefact-et-maitrise/" },
    { name: "Gnishak Roi-souris", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gnishak-roi-souris-artefact-et-maitrise/" },
    { name: "Goffred Porte-cuivre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-goffred-porte-cuivre-artefact-et-maitrise/" },
    { name: "Gorgédesang", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gorgedesang-artefact-et-maitrise/" },
    { name: "Gardien Prysma", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-grand-gardien-prysma-artefact-et-maitrise/" },
    { name: "Granyt Garde-porte", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-granyt-garde-porte-artefact-et-maitrise/" },
    { name: "Gretel Fléau-Harpie", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gretel-fleau-harpie-artefact-et-maitrise/" },
    { name: "Gros Bill", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gros-bill-artefact-et-maitrise/" },
    { name: "Gurgoth l'Augure", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gurgoth-laugure-artefact-et-maitrise/" },
    { name: "Gwyndolin la Muette", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gwyndolin-la-muette-guerriere-artefact-et-maitrise/" },
    { name: "Hansel le Chasseur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hansel-le-chasseur-artefact-et-maitrise/" },
    { name: "Harima", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-harima-artefact-et-maitrise/" },
    { name: "Hégémon", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hegemon-artefact-et-maitrise/" },
    { name: "Helior", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-helior-artefact-et-maitrise/" },
    { name: "Ignatius", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ignatius-artefact-et-maitrise/" },
    { name: "Inithwe Doublesang", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-inithwe-doublesang-artefact-et-maitrise/" },
    { name: "Ithos", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ithos-artefact-et-maitrise/" },
    { name: "Iudex Artor", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-iudex-artor-artefact-et-maitrise/" },
    { name: "Jagg Scie d'os", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jagg-scie-dos-artefact-et-maitrise/" },
    { name: "Jetni la Géante", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jetni-la-geante-artefact-et-maitrise/" },
    { name: "Kaja l'Ironique", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kaja-lironique-artefact-et-maitrise/" },
    { name: "Kantra le Cyclone", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kantra-le-cyclone-artefact-et-maitrise/" },
    { name: "Karato le Chasseur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-karato-le-chasseur-artefact-et-maitrise/" },
    { name: "Karilon le Sonneur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-karilon-le-sonneur-artefact-et-maitrise/" },
    { name: "Keeyra L'Observateur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-keeyra-lobservateur-artefact-et-maitrise/" },
    { name: "Kerin le Moissonneur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kerin-le-moissonneur-artefact-et-maitrise/" },
    { name: "Khoronar", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-khoronar-artefact-et-maitrise/" },
    { name: "Konstantin le Diurne", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-konstantin-le-diurne-artefact-et-maitrise/" },
    { name: "Korugar Clochemort", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-korugar-clochemort-artefact-et-maitrise/" },
    { name: "Krok'mar le Dévoreur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-krokmar-le-devoreur-artefact-et-maitrise/" },
    { name: "Lanakis l'Élue", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lanakis-lelue-artefact-et-maitrise/" },
    { name: "Balar le Perdu", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-balar-le-perdu-artefact-et-maitrise/" },
    { name: "Loki le Trompeur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-loki-le-trompeur-artefact-et-maitrise/" },
    { name: "Longuebarbe", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-longuebarbe-artefact-et-maitrise/" },
    { name: "Losan K'Leth", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-losan-kleth-artefact-et-maitrise/" },
    { name: "Lysanthir Tue-bêtes", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lysanthir-tue-betes-artefact-et-maitrise/" },
    { name: "Lyssandra", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lyssandra-artefact-et-maitrise/" },
    { name: "Maranix", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-maranix-artefact-et-maitrise/" },
    { name: "Matriarche Zarguna", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-matriarche-zarguna-artefact-et-maitrise/" },
    { name: "Maulie Chope", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-maulie-chope-artefact-et-maitrise/" },
    { name: "Mère Cybèle", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mere-cybele-artefact-et-maitrise/" },
    { name: "Michelangelo", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-michelangelo-artefact-et-maitrise/" },
    { name: "Michinaki", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-michinaki-artefact-et-maitrise/" },
    { name: "Modo du Carillon", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-modo-du-carillon-equipement-et-maitrise/" },
    { name: "Morrigaine", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-morrigaine-artefact-et-maitrise/" },
    { name: "Musclor", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-musclor-artefact-et-maitrise/" },
    { name: "Nari le chanceux", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nari-le-chanceux-artefact-et-maitrise/" },
    { name: "Narma la ressuscitée", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-narma-la-ressuscitee-artefact-et-maitrise/" },
    { name: "Narses Roi Spectre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-narses-roi-spectre-artefact-et-maitrise/" },
    { name: "Néspectre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nespectre-artefact-et-maitrise/" },
    { name: "Odin Patriarche", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-odin-patriarche-artefact-et-maitrise/" },
    { name: "Oella", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-oella-artefact-et-maitrise/" },
    { name: "Onryo leyasu", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-onryo-leyasu-artefact-et-maitrise/" },
    { name: "Osgrun le Corrupteur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-osgrun-le-corrupteur-artefact-et-maitrise/" },
    { name: "Padraig Grand Chène", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-padraig-grand-chene-artefact-et-maitrise/" },
    { name: "Prophétesse Aveugle", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-prophetesse-aveugle-artefact-et-maitrise/" },
    { name: "Raé", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rae-artefact-et-maitrise/" },
    { name: "Raf-Matab", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-raf-matab-artefact-et-maitrise/" },
    { name: "Rakka Vilevague", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rakka-vilevague-artefact-et-maitrise/" },
    { name: "Raphael", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-raphael-artefact-et-maitrise/" },
    { name: "Rathalos l'Epeiste", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rathalos-lepeiste-artefact-et-maitrise/" },
    { name: "Rhazin Peaumarquée", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-rhazin-peaumarquee-artefact-et-maitrise/" },
    { name: "Riho Lance d'Os", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-riho-lance-dos-artefact-et-maitrise/" },
    { name: "Robar", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-robar-artefact-et-maitrise/" },
    { name: "Roi Gallcobar", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roi-gallcobar-artefact-et-maitrise/" },
    { name: "Ronda", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ronda-artefact-et-maitrise/" },
    { name: "Roshcard la tour", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roshcard-la-tour-artefact-et-maitrise/" },
    { name: "Roxam", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roxam-artefact-et-maitrise/" },
    { name: "Ruarc Gardienvert", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ruarc-gardienvert-artefact-et-maitrise/" },
    { name: "Ruel Maître-Chasseur", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ruel-maitre-chasseur-artefact-et-maitrise/" },
    { name: "Saito", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-saito-artefact-et-maitrise/" },
    { name: "Sanguine Maria", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sanguine-maria-artefact-et-maitrise/" },
    { name: "Sans âme", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sans-ame-soulless-artefact-et-maitrise/" },
    { name: "Searsha la Calcinée", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-searsha-la-calcinee-artefact-et-maitrise/" },
    { name: "Senna Cœur d'ambre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-senna-coeur-dambre-artefact-et-maitrise/" },
    { name: "Septimus", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-septimus-artefact-et-maitrise/" },
    { name: "Séthallia", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sethallia-artefact-et-maitrise/" },
    { name: "Shemnath", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-shemnath-artefact-et-maitrise/" },
    { name: "Shredder", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-shredder-artefact-et-maitrise/" },
    { name: "Shu-Zhen la Brave", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-shu-zhen-la-brave-artefact-et-maitrise/" },
    { name: "Sigmund le bouclier", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sigmund-le-bouclier-artefact-et-maitrise/" },
    { name: "Sniktraak", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sniktraak-artefact-et-maitrise/" },
    { name: "Stokk le Brisé", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-stokk-le-brise-artefact-et-maitrise/" },
    { name: "Strategos Islin", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-strategos-islin-artefact-et-maitrise/" },
    { name: "Sun Wukong", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-sun-wukong-artefact-et-maitrise/" },
    { name: "Suzerain Katonn", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-suzerain-katonn-artefact-et-maitrise/" },
    { name: "Tatura Peau de Givre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tatura-peau-de-givre-artefact-et-maitrise/" },
    { name: "Thor au Marteau", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-thor-au-marteau-artefact-et-maitrise/" },
    { name: "Togron le Siamois", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-togron-le-siamois-artefact-et-maitrise/" },
    { name: "Tholin Barbe-infâme", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tholin-barbe-infame-artefact-et-maitrise/" },
    { name: "Tribun Héraklétès", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tribun-herakletes-artefact-et-maitrise/" },
    { name: "Truath", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-truath-artefact-et-maitrise/" },
    { name: "Tuhanarak", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tuhanarak-artefact-et-maitrise/" },
    { name: "Tusskor Prime-hache", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tusskor-prime-hache-equipement-et-maitrise/" },
    { name: "Tyran Ixlimor", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tyran-ixlimor-artefact-et-maitrise/" },
    { name: "Ugir Mange-dragon", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ugir-mange-dragon-artefact-et-maitrise/" },
    { name: "Uzol du Jade", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-uzol-du-jade-artefact-et-maitrise/" },
    { name: "Valkanen", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valkanen-artefact-et-maitrise/" },
    { name: "Vasal du sceau", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vasal-du-sceau-artefact-et-maitrise/" },
    { name: "Venalicia Mère-serfs", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-venalicia-mere-serfs-artefact-et-maitrise/" },
    { name: "Versulf Le Lugubre", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-versulf-le-lugubre-artefact-et-maitrise/" },
    { name: "Vitrius l'Oint", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vitrius-loint-artefact-et-maitrise/" },
    { name: "Vizir Ovelis", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vizir-ovelis-artefact-et-maitrise/" },
    { name: "Vizug le Toxique", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vizug-le-toxique-artefact-et-maitrise/" },
    { name: "Vlad le nocturne", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vlad-le-nocturne-artefact-et-maitrise/" },
    { name: "Wythir la couronnée", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-wythir-la-couronnee-artefact-et-maitrise/" },
    { name: "Xena: Princesse Guerrière", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-xena-princesse-guerriere-artefact-et-maitrise/" },
    { name: "Yakarl le Fléau", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yakarl-le-fleau-artefact-et-maitrise/" },
    { name: "Yannica", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yannica-artefact-et-maitrise/" },
    { name: "Zinogre l'Epeiste", rarity: "Légendaire", rank: "A", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-zinogre-lepeiste-artefact-et-maitrise/" },

    // Légendaire Rang B (Bon) - 74 champions
    { name: "Aleksandr Tireur d'élite", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-aleksandr-tireur-delite-artefact-et-maitrise/" },
    { name: "Ankora Reine Spectre", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ankora-reine-spectre-artefact-et-maitrise/" },
    { name: "Annaliste Adelyn", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-annaliste-adelyn-artefact-et-maitrise/" },
    { name: "April O'Neil", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-april-oneil-artefact-et-maitrise/" },
    { name: "Arix", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-arix-artefact-et-maitrise/" },
    { name: "Astralithe", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-astralithe-artefact-et-maitrise/" },
    { name: "Athel Suprême", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-athel-supreme-artefact-et-maitrise/" },
    { name: "Bambus Trèfle", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bambus-trefle-artefact-et-maitrise/" },
    { name: "Basileus Roanas", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-basileus-roanas-artefact-et-maitrise/" },
    { name: "Bystophus", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-bystophus-artefact-et-maitrise/" },
    { name: "Chefdeguerre", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chefdeguerre-artefact-et-maitrise/" },
    { name: "Chef de meute Shy'ek", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chef-de-meute-shyek-artefact-et-maitrise/" },
    { name: "Chevalier noir", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-chevalier-noir-artefact-et-maitrise/" },
    { name: "Cillian le Chanceux", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cillian-le-chanceux-artefact-et-maitrise/" },
    { name: "Craklin le Noirci", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-craklin-le-noirci-artefact-et-maitrise/" },
    { name: "Cromax Sanglune", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-cromax-sanglune-artefact-et-maitrise/" },
    { name: "Damoiselle Annie", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-damoiselle-annie-artefact-et-maitrise/" },
    { name: "Déliana", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-deliana-artefact-et-maitrise/" },
    { name: "Drokgul le Hâvre", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-drokgul-le-have-artefact-et-maitrise/" },
    { name: "Elegaius", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-elegaius-artefact-et-maitrise/" },
    { name: "Elénaril", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-elenaril-artefact-et-maitrise/" },
    { name: "Errol", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-errol-artefact-et-maitrise/" },
    { name: "Fatalis l'Epeiste", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-fatalis-lepeiste-artefact-et-maitrise/" },
    { name: "Galek Ultime", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-galek-ultime1-artefact-et-maitrise/" },
    { name: "Ginro la Cigogne", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ginro-la-cigogne-artefact-et-maitrise/" },
    { name: "Graal Roi de Crypte", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-graal-roi-de-crypte-artefact-et-maitrise/" },
    { name: "Greggor Lord de lune", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-greggor-lord-de-lune-artefact-et-maitrise/" },
    { name: "Gurptuk Barbe-Mousse", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gurptuk-barbe-mousse-artefact-et-maitrise/" },
    { name: "Hakkorhn Fracapacha", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-hakkorhn-fracapacha-artefact-et-maitrise/" },
    { name: "Holsring", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-holsring-artefact-et-maitrise/" },
    { name: "Jack le Moissonneur", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jack-le-moissonneur-artefact-et-maitrise/" },
    { name: "Kawn Brise-branche", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-kawn-brise-branche-equipement-et-maitrise/" },
    { name: "Leminisi Aile-dorée", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-leminisi-aile-doree-artefact-et-maitrise/" },
    { name: "L'Incarnée", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lincarnee-artefact-et-maitrise/" },
    { name: "Lonatharil", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lonatharil-artefact-et-maitrise/" },
    { name: "Lord champfort", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lord-champfort-artefact-et-maitrise/" },
    { name: "Lord Shazar", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lord-shazar-artefact-et-maitrise/" },
    { name: "Loriaca Beau-Sabot", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-loriaca-beau-sabot-artefact-et-maitrise/" },
    { name: "Lugan l'Inébranlable", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lugan-linebranlable-artefact-et-maitrise/" },
    { name: "Mathias Fléau-noir", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mathias-fleau-noir-artefact-et-maitrise/" },
    { name: "Mère de Guerre", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mere-de-guerre-artefact-et-maitrise/" },
    { name: "Minaya", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-minaya-artefact-et-maitrise/" },
    { name: "Nobel", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nobel-artefact-et-maitrise/" },
    { name: "Noct le Paralyseur", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-noct-le-paralyseur-artefact-et-maitrise/" },
    { name: "Norog", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-norog-artefact-et-maitrise/" },
    { name: "Opardin chef de clan", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-opardin-chef-de-clan-artefact-et-maitrise/" },
    { name: "Parle-nuées Zyclic", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-parle-nuees-zyclic-artefact-et-maitrise/" },
    { name: "Praeva l'Ondulante", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-praeva-londulante-artefact-et-maitrise/" },
    { name: "Pyxniel", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-pyxniel-artefact-et-maitrise/" },
    { name: "Razelvarg", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-razelvarg-artefact-et-maitrise/" },
    { name: "Reine éva", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-reine-eva-artefact-et-maitrise/" },
    { name: "Richtoff l'Effronté", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-richtoff-leffronte-artefact-et-maitrise/" },
    { name: "Roi de la montagne", rarity: "Légendaire", rank: "B", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roi-de-la-montagne-artefact-et-maitrise/" },
    { name: "Roi Garog", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roi-garog-artefact-et-maitrise/" },
    { name: "Roric Poison-dragon", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-roric-poison-dragon-artefact-et-maitrise/" },
    { name: "Samar Maudigemme", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-samar-maudigemme-artefact-et-maitrise/" },
    { name: "Samson le Pilon", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-samson-le-pilon-artefact-et-maitrise/" },
    { name: "Shirimani", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-shirimani-artefact-et-maitrise/" },
    { name: "Skarg l'Ancien", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-skarg-lancien-artefact-et-maitrise/" },
    { name: "Skartorsis", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-skartorsis-artefact-et-maitrise/" },
    { name: "Skeletor", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-skeletor-artefact-et-maitrise/" },
    { name: "Skorid Semi-engendré", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-skorid-semi-engendre-artefact-et-maitrise/" },
    { name: "Tatsu", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tatsu-artefact-et-maitrise/" },
    { name: "Teela Toisongore", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-teela-toisongore-artefact-et-maitrise/" },
    { name: "Théa Ange Tombal", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-thea-ange-tombal-artefact-et-maitrise/" },
    { name: "Timit le Bouffon", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-timit-le-bouffon-artefact-et-maitrise/" },
    { name: "Tramaria", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-tramaria-artefact-et-maitrise/" },
    { name: "Trèfle", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-trefle-artefact-et-maitrise/" },
    { name: "Ultan la Carapace", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-ultan-la-carapace-artefact-et-maitrise/" },
    { name: "Valet de Cœur", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-valet-de-coeur-artefact-et-maitrise/" },
    { name: "Varl le destructeur", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-varl-le-destructeur-artefact-et-maitrise/" },
    { name: "Visix l'Insoumise", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-visix-linsoumise-artefact-et-maitrise/" },
    { name: "Wurlim Roi du Gel", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-wurlim-roi-du-gel-artefact-et-maitrise/" },
    { name: "Yoshi l'ivrogne", rank: "B", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-yoshi-livrogne-artefact-et-maitrise/" },

    // Légendaires Rang C (7 champions)
    { name: "Gomlok Peau Céleste", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-gomlok-peau-celeste-artefact-et-maitrise/" },
    { name: "Grohak l'Ensanglanté", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-grohak-lensanglante-artefact-et-maitrise/" },
    { name: "Guurda Brassemarais", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-guurda-brassemarais-artefact-et-maitrise/" },
    { name: "Lord crâne var-Gall", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-lord-crane-var-gall-artefact-et-maitrise/" },
    { name: "Mortu-Macaab", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-mortu-macaab-artefact-et-maitrise/" },
    { name: "Nogdar Chasse-têtes", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-nogdar-chasse-tetes-artefact-et-maitrise/" },
    { name: "Vergumkaar", rank: "C", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-vergumkaar-artefact-et-maitrise/" },

    // Légendaires Rang D (1 champion)
    { name: "Jingwon", rank: "D", rarity: "Légendaire", url: "https://www.alucare.fr/wiki/guide-raid-shadow-legend/guide-sur-jingwon-artefact-et-maitrise/" }
];

module.exports = champions;